channels:
- conda-forge
dependencies:
- python=3.8.20
- pip<=24.3.1
- pip:
  - mlflow==2.15.1
  - cffi==1.17.0
  - cloudpickle==3.1.0
  - lightgbm==4.6.0
  - matplotlib==3.7.3
  - pandas==2.0.3
  - psutil==6.0.0
  - pyarrow==15.0.2
  - scikit-learn==1.3.2
name: mlflow-env
